// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	UniqueID             string               `protobuf:"bytes,1,opt,name=uniqueID,proto3" json:"uniqueID,omitempty"`
	Username             string               `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash         string               `protobuf:"bytes,4,opt,name=passwordHash,proto3" json:"passwordHash,omitempty"`
	FirstName            string               `protobuf:"bytes,5,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string               `protobuf:"bytes,6,opt,name=lastName,proto3" json:"lastName,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,7,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Avatar               string               `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Confirmed            bool                 `protobuf:"varint,9,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Role                 string               `protobuf:"bytes,10,opt,name=role,proto3" json:"role,omitempty"`
	RegisterDate         *timestamp.Timestamp `protobuf:"bytes,11,opt,name=registerDate,proto3" json:"registerDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUniqueID() string {
	if m != nil {
		return m.UniqueID
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetConfirmed() bool {
	if m != nil {
		return m.Confirmed
	}
	return false
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetRegisterDate() *timestamp.Timestamp {
	if m != nil {
		return m.RegisterDate
	}
	return nil
}

type UserFilter struct {
	UserID               []string `protobuf:"bytes,1,rep,name=userID,proto3" json:"userID,omitempty"`
	Email                []string `protobuf:"bytes,2,rep,name=email,proto3" json:"email,omitempty"`
	Username             []string `protobuf:"bytes,3,rep,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserFilter) Reset()         { *m = UserFilter{} }
func (m *UserFilter) String() string { return proto.CompactTextString(m) }
func (*UserFilter) ProtoMessage()    {}
func (*UserFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFilter.Unmarshal(m, b)
}
func (m *UserFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFilter.Marshal(b, m, deterministic)
}
func (m *UserFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFilter.Merge(m, src)
}
func (m *UserFilter) XXX_Size() int {
	return xxx_messageInfo_UserFilter.Size(m)
}
func (m *UserFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFilter.DiscardUnknown(m)
}

var xxx_messageInfo_UserFilter proto.InternalMessageInfo

func (m *UserFilter) GetUserID() []string {
	if m != nil {
		return m.UserID
	}
	return nil
}

func (m *UserFilter) GetEmail() []string {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *UserFilter) GetUsername() []string {
	if m != nil {
		return m.Username
	}
	return nil
}

type UserResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *UserResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*UserFilter)(nil), "proto.UserFilter")
	proto.RegisterType((*UserResponse)(nil), "proto.UserResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4f, 0x8f, 0xd3, 0x30,
	0x10, 0xc5, 0x69, 0xd3, 0x94, 0x76, 0xd2, 0x0b, 0x06, 0x21, 0xab, 0x42, 0xa2, 0xe4, 0xd4, 0xcb,
	0x26, 0xa2, 0xdc, 0x10, 0xe2, 0x00, 0x2b, 0x16, 0x2e, 0x7b, 0x08, 0x7f, 0x0e, 0xdc, 0xdc, 0x74,
	0x9a, 0x58, 0x4a, 0x62, 0xaf, 0xed, 0x2c, 0xe2, 0xcb, 0xf2, 0x59, 0x90, 0xc7, 0xe9, 0x36, 0xbd,
	0xed, 0xc9, 0x79, 0xf3, 0x1b, 0xcf, 0x3c, 0xbd, 0x18, 0xa0, 0xb7, 0x68, 0x32, 0x6d, 0x94, 0x53,
	0x2c, 0xa6, 0x63, 0xfd, 0xba, 0x52, 0xaa, 0x6a, 0x30, 0x27, 0xb5, 0xef, 0x8f, 0xb9, 0x93, 0x2d,
	0x5a, 0x27, 0x5a, 0x1d, 0xfa, 0xd2, 0x7f, 0x53, 0x98, 0xfd, 0xb4, 0x68, 0xd8, 0x1a, 0x16, 0x7d,
	0x27, 0xef, 0x7a, 0xfc, 0x76, 0xcd, 0x27, 0x9b, 0xc9, 0x76, 0x59, 0x3c, 0x68, 0x62, 0x16, 0x4d,
	0x27, 0x5a, 0xe4, 0xd3, 0x81, 0x0d, 0x9a, 0xbd, 0x80, 0x18, 0x5b, 0x21, 0x1b, 0x1e, 0x11, 0x08,
	0x82, 0xa5, 0xb0, 0xd2, 0xc2, 0xda, 0x3f, 0xca, 0x1c, 0xbe, 0x0a, 0x5b, 0xf3, 0x19, 0xc1, 0x8b,
	0x1a, 0x7b, 0x05, 0xcb, 0xa3, 0x34, 0xd6, 0xdd, 0xfa, 0xb1, 0x31, 0x35, 0x9c, 0x0b, 0x7e, 0x67,
	0x23, 0x06, 0x38, 0x0f, 0x3b, 0x4f, 0x9a, 0x6d, 0x20, 0xd1, 0xb5, 0xea, 0xf0, 0xb6, 0x6f, 0xf7,
	0x68, 0xf8, 0x53, 0xc2, 0xe3, 0x12, 0x7b, 0x09, 0x73, 0x71, 0x2f, 0x9c, 0x30, 0x7c, 0x41, 0x70,
	0x50, 0x7e, 0x67, 0xa9, 0xba, 0xa3, 0x34, 0x2d, 0x1e, 0xf8, 0x72, 0x33, 0xd9, 0x2e, 0x8a, 0x73,
	0x81, 0x31, 0x98, 0x19, 0xd5, 0x20, 0x07, 0xba, 0x43, 0xdf, 0xec, 0x23, 0xac, 0x0c, 0x56, 0xd2,
	0x3a, 0x34, 0xd7, 0xc2, 0x21, 0x4f, 0x36, 0x93, 0x6d, 0xb2, 0x5b, 0x67, 0x21, 0xd8, 0xec, 0x14,
	0x6c, 0xf6, 0xe3, 0x14, 0x6c, 0x71, 0xd1, 0x9f, 0xfe, 0x02, 0xf0, 0xf9, 0x7e, 0x91, 0x8d, 0x0b,
	0xbe, 0x7c, 0x72, 0x94, 0x71, 0xe4, 0x7d, 0x05, 0x75, 0x4e, 0x71, 0x4a, 0xe5, 0x21, 0xc5, 0x71,
	0xee, 0x11, 0x81, 0x07, 0x9d, 0xde, 0xc0, 0xca, 0xcf, 0x2d, 0xd0, 0x6a, 0xd5, 0x59, 0x64, 0x6f,
	0x20, 0xf6, 0xcc, 0xd2, 0xe0, 0x64, 0x97, 0x04, 0x67, 0x19, 0xf5, 0x04, 0xe2, 0x97, 0x94, 0xaa,
	0xef, 0x1c, 0xfd, 0xc3, 0xa8, 0x08, 0x62, 0x77, 0x07, 0x89, 0x6f, 0xfa, 0x8e, 0xe6, 0x5e, 0x96,
	0xc8, 0x72, 0x88, 0x6e, 0xd0, 0xb1, 0x67, 0xa3, 0xfb, 0xc1, 0xfb, 0xfa, 0xf9, 0x78, 0xe4, 0xb0,
	0x36, 0x7d, 0xc2, 0xde, 0x42, 0xfc, 0xd9, 0x0f, 0x7a, 0xfc, 0x95, 0x4f, 0x1f, 0x7e, 0xbf, 0xaf,
	0xa4, 0xab, 0xfb, 0x7d, 0x56, 0xaa, 0xd6, 0x3f, 0x49, 0xe5, 0xea, 0xab, 0xbf, 0xb9, 0x2d, 0x8d,
	0xd0, 0x9d, 0x72, 0x78, 0x25, 0xb4, 0xcc, 0x0f, 0xc2, 0x89, 0x8c, 0x8c, 0xe7, 0x5e, 0x1a, 0x5d,
	0x0e, 0xaf, 0x78, 0x4e, 0xc7, 0xbb, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x83, 0x13, 0x1d,
	0xef, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Get(ctx context.Context, in *UserFilter, opts ...grpc.CallOption) (*UserResponse, error)
	Count(ctx context.Context, in *UserFilter, opts ...grpc.CallOption) (*UserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Get(ctx context.Context, in *UserFilter, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Count(ctx context.Context, in *UserFilter, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/proto.UserService/Count", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Get(context.Context, *UserFilter) (*UserResponse, error)
	Count(context.Context, *UserFilter) (*UserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Get(ctx context.Context, req *UserFilter) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedUserServiceServer) Count(ctx context.Context, req *UserFilter) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Count not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*UserFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Count",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Count(ctx, req.(*UserFilter))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _UserService_Count_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
